const aTypes = {
    CREATE_TODO_TASK: 'CREATE_TODO_TASK',
    CREATE_TODO_TASK_FULFILLED: 'CREATE_TODO_TASK_FULFILLED',
    CREATE_TODO_TASK_REJECTED: 'CREATE_TODO_TASK_REJECTED',
    CHANGE_TODO_TASK: 'CHANGE_TODO_TASK',
    CHANGE_TODO_TASK_FULFILLED: 'CHANGE_TODO_TASK_FULFILLED',
    CHANGE_TODO_TASK_REJECTED: 'CHANGE_TODO_TASK_REJECTED',
    DONE_TODO_TASK: 'DONE_TODO_TASK',
    DONE_TODO_TASK_FULFILLED: 'DONE_TODO_TASK_FULFILLED',
    DONE_TODO_TASK_REJECTED: 'DONE_TODO_TASK_REJECTED',
    DELETE_TODO_TASK: 'DELETE_TODO_TASK',
    DELETE_TODO_TASK_FULFILLED: 'DELETE_TODO_TASK_FULFILLED',
    DELETE_TODO_TASK_REJECTED: 'DELETE_TODO_TASK_REJECTED',
    GET_TODO_TASKS_FOR_DATE: 'GET_TODO_TASKS_FOR_DATE',
    GET_TODO_TASKS_FOR_DATE_FULFILLED: 'GET_TODO_TASKS_FOR_DATE_FULFILLED',
    GET_TODO_TASKS_FOR_DATE_REJECTED: 'GET_TODO_TASKS_FOR_DATE_REJECTED',
    SET_MUTABLE_ITEM_ID: 'SET_MUTABLE_ITEM_ID',
    SET_MUTABLE_ITEM_DATE: 'SET_MUTABLE_ITEM_DATE',
    SET_MUTABLE_ITEM_TASK_TEXT: 'SET_MUTABLE_ITEM_TASK_TEXT',
};

export default aTypes;
